[versions]
agp = "8.4.0"
kotlin = "1.9.23"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.8.3"
activityCompose = "1.9.0"
composeBom = "2024.05.00"
navigation-compose =  "2.7.7"
appcompat = "1.6.1"
material = "1.12.0"
error-phone-gradle-plugin = "3.1.0"
error-phone = "2.27.1"
ktor = "2.3.11"
ksp = "1.9.23-1.0.19"
kotlin-poet = "1.16.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" , version = "1.3.0-alpha06"}
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose"}
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
error-phone = { module = "com.google.errorprone:error_prone_core", version.ref = "error-phone"}
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-engine-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
# TODO: Cant use in KMP, would like to use other mock library instead.
mockk = { module = "io.mockk:mockk", version = "1.13.10"}
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp"}
kotlin-poet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlin-poet"}
kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlin-poet"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
error-phone = { id = "net.ltgt.errorprone", version.ref = "error-phone-gradle-plugin"}
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
